apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: dev
  labels:
    app: test
spec:
  serviceAccountName: dev-sa
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","3600"]
