apiVersion: batch/v1
kind: Job
metadata:
  name: one-time-job
  namespace: pe-day-jobs
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: job
          image: busybox
          command: ["sh", "-c", "echo Job Started; sleep 5; echo Job Completed"]
