apiVersion: v1
kind: Pod
metadata:
  name: cgroup-demo-fixed
spec:
  containers:
  - name: app
    image: polinux/stress
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "200M", "--vm-hang", "1"]
    resources:
      limits:
        memory: "256Mi"
