apiVersion: v1
kind: Pod
metadata:
  name: test-pod-with-toleration
spec:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx:1.25
