apiVersion: v1
kind: Pod
metadata:
  name: affinity-break
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - nvme   # <-- does NOT exist (break)
  containers:
    - name: nginx
      image: nginx:1.25
